repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.11.7'
    hooks:
    - id: ruff
      name: linting code with Ruff
      args: [ "--fix" ]
    - id: ruff-format
      name: format code using Ruff formatter
