strategies:
   llama_vision:
      class: text_extract_api.extract.strategies.llama_vision.LlamaVisionStrategy
   marker:
      class: text_extract_api.extract.strategies.marker.MarkerStrategy
   tesseract:
      class: text_extract_api.extract.strategies.tesseract.TesseractStrategy
