strategies:
   llama_vision:
      class: text_extract_api.extract.strategies.llama_vision.LlamaVisionStrategy
   minicpm_v:
      class: text_extract_api.extract.strategies.minicpm_v.MiniCPMVStrategy
   easyocr:
      class: text_extract_api.extract.strategies.easyocr.EasyOCRStrategy
   marker:
      class: text_extract_api.extract.strategies.marker.MarkerStrategy
