strategies:
   llama_vision:
      class: text_extract_api.extract.strategies.llama_vision.LlamaVisionStrategy
   marker:
      class: text_extract_api.extract.strategies.marker.MarkerStrategy
   easyocr:
      class: text_extract_api.extract.strategies.easyocr.EasyOCRStrategy
